/**
 * Source: "1001 Albums You Must Hear Before You Die"
 * Data from: CSV file
 * Metadata from: iTunes Search API
 *
 * This file is auto-generated by scripts/convert-albums-data.ts
 */

export interface AlbumSeed {
  title: string;
  artist: string;
  year: number;
  list_number: number;
  genre?: string;
  cover_url?: string;
}

export const albumsList: AlbumSeed[] = [
  { title: "In The Wee Small Hours", artist: "Frank Sinatra", year: 1955, list_number: 1, genre: "Vocal", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/97/a7/42/97a7424f-8161-052f-ce3c-93730c2d30de/14UMGIM32540.rgb.jpg/600x600bb.jpg" },
  { title: "Ellington at Newport '56", artist: "Duke Ellington", year: 1956, list_number: 2, genre: "Jazz", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music1/v4/07/b2/61/07b26127-2169-d5db-efa5-559d422a9d31/886445222135.jpg/600x600bb.jpg" },
  { title: "Elvis Presley", artist: "Elvis Presley", year: 1956, list_number: 3, genre: "Pop", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/c2/21/a8/c221a818-bc9f-675a-cecb-7dbc3bbe17a4/886444095242.jpg/600x600bb.jpg" },
  { title: "Songs For Swingin' Lovers", artist: "Frank Sinatra", year: 1956, list_number: 4, genre: "Vocal Pop", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/9d/ae/86/9dae867b-e8dc-5e83-9079-bacd32aa1da7/15UMGIM78881.rgb.jpg/600x600bb.jpg" },
  { title: "Birth of the Cool", artist: "Miles Davis", year: 1956, list_number: 5, genre: "Jazz", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/c2/0b/d4/c20bd438-fc2b-f911-bcd7-793c50c2961f/05099963651850.rgb.jpg/600x600bb.jpg" },
  { title: "Tragic Songs Of Life", artist: "The Louvin Brothers", year: 1956, list_number: 6, genre: "Rock", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music122/v4/75/f3/3e/75f33e51-2fdd-0d05-3113-437f158b5fc2/190295012960.jpg/600x600bb.jpg" },
  { title: "The Atomic Mr Basie", artist: "Count Basie", year: 1957, list_number: 7, genre: "Pop", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music/v4/58/8e/e8/588ee868-ed57-a7e8-050a-7ae1a929678c/5099930605459_1484x1484_300dpi.jpg/600x600bb.jpg" },
  { title: "This is Fats Domino", artist: "Fats Domino", year: 1957, list_number: 8, genre: "R&B/Soul", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/d4/78/a4/d478a4fb-a5ef-d577-7232-8c2a60ebea46/00724353760052.rgb.jpg/600x600bb.jpg" },
  { title: "Here's Little Richard", artist: "Little Richard", year: 1957, list_number: 9, genre: "Rock", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music128/v4/6a/59/ba/6a59ba83-b62c-0aba-afdf-70112572352d/00888072025745.rgb.jpg/600x600bb.jpg" },
  { title: "The Wildest", artist: "Louis Prima", year: 1957, list_number: 10, genre: "Vocal Jazz", cover_url: "https://is1-ssl.mzstatic.com/image/thumb/Music6/v4/38/ae/ef/38aeefd0-476e-ccdc-a5b8-441c54578d5e/00724353869656.jpg/600x600bb.jpg" }
];
