/**
 * Source: "1001 Movies You Must See Before You Die" book
 * Metadata from: TMDB API
 *
 * This file is auto-generated by scripts/fetch-tmdb-data.ts
 */

export interface MovieSeed {
  title: string;
  director: string;
  year: number;
  list_number: number;
  genre?: string;
  poster_url?: string;
  runtime?: number;
  description?: string;
  tmdb_id?: number;
  watch_provider_link?: string;
}

export const moviesList: MovieSeed[] = [
  { title: "Le Voyage Dans La Lune", director: "Georges Méliès", year: 1902, list_number: 1, genre: "Adventure", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/9o0v5LLFk51nyTBHZSre6OB37n2.jpg", runtime: 15, description: "Professor Barbenfouillis and five of his colleagues from the Academy of Astronomy travel to the Moon aboard a rocket propelled by a giant cannon. Once on the lunar surface, the bold explorers face the many perils hidden in the caves of the mysterious planet.", tmdb_id: 775, watch_provider_link: "https://www.themoviedb.org/movie/775-le-voyage-dans-la-lune/watch?locale=US" },
  { title: "The Great Train Robbery", director: "Edwin S. Porter", year: 1903, list_number: 2, genre: "Western", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vEYr1sJR1dOFGXwXawpBN6hDRGF.jpg", runtime: 12, description: "After the train station clerk is assaulted and left bound and gagged, then the departing train and its passengers robbed, a posse goes in hot pursuit of the fleeing bandits.", tmdb_id: 5698, watch_provider_link: "https://www.themoviedb.org/movie/5698-the-great-train-robbery/watch?locale=US" },
  { title: "The Birth of a Nation", director: "D.W. Griffith", year: 1915, list_number: 3, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/f9MkgI1ObRVvJwWgJyWtRbgyWng.jpg", runtime: 195, description: "Two families, abolitionist Northerners the Stonemans and Southern landowners the Camerons, intertwine. When Confederate colonel Ben Cameron is captured in battle, nurse Elsie Stoneman petitions for his pardon. In Reconstruction-era South Carolina, Cameron founds the Ku Klux Klan, battling Elsie's congressman father and his African-American protégé, Silas Lynch.", tmdb_id: 618, watch_provider_link: "https://www.themoviedb.org/movie/618-the-birth-of-a-nation/watch?locale=US" },
  { title: "Les Vampires", director: "Louis Feuillade", year: 1916, list_number: 4, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/8jO0Zmd468zS9WRLHpwsKUowZAX.jpg", runtime: 422, description: "Paris is prey to an invisible terror against which the police can do nothing: a sinister organization that sows chaos and death. The intrepid journalist Philippe Guérande and his partner embark on a long crusade to put an end to the crimes of the Great Vampire and Irma Vep, his dangerous accomplice. (A ten episode movie serial.)", tmdb_id: 29082 },
  { title: "Intolerance", director: "D.W. Griffith", year: 1916, list_number: 5, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/lJCabs4TMOsKfnl0BmA5Hf16Ezb.jpg", runtime: 197, description: "The story of a poor young woman, separated by prejudice from her husband and baby, is interwoven with tales of intolerance from throughout history.", tmdb_id: 3059, watch_provider_link: "https://www.themoviedb.org/movie/3059-intolerance-love-s-struggle-throughout-the-ages/watch?locale=US" },
  { title: "The Cabinet of Dr. Caligari", director: "Robert Wiene", year: 1920, list_number: 6, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/myK9DeIsXWGKgUTZyGXg2IfFk0W.jpg", runtime: 77, description: "Francis, a young man, recalls in his memory the horrible experiences he and his fiancée Jane recently went through. Francis and his friend Alan visit The Cabinet of Dr. Caligari, an exhibit where the mysterious doctor shows the somnambulist Cesare, and awakens him for some moments from his death-like sleep.", tmdb_id: 234, watch_provider_link: "https://www.themoviedb.org/movie/234-das-cabinet-des-dr-caligari/watch?locale=US" },
  { title: "Broken Blossoms", director: "D.W. Griffith", year: 1919, list_number: 7, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/njwFIUL76zaRmPemnrZVmmTSCjz.jpg", runtime: 89, description: "The love story of an abused English girl and a Chinese Buddhist in a time when London was a brutal and harsh place to live.", tmdb_id: 899, watch_provider_link: "https://www.themoviedb.org/movie/899-broken-blossoms-or-the-yellow-man-and-the-girl/watch?locale=US" },
  { title: "Way Down East", director: "D.W. Griffith", year: 1920, list_number: 8, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/xzrSiQuiSb5hKePkU9AFuCcgRxE.jpg", runtime: 150, description: "A naive country girl is tricked into a sham marriage by a wealthy womanizer, then must rebuild her life despite the taint of having borne a child out of wedlock.", tmdb_id: 31509, watch_provider_link: "https://www.themoviedb.org/movie/31509-way-down-east/watch?locale=US" },
  { title: "Within Our Gates", director: "Oscar Micheaux", year: 1920, list_number: 9, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/uz1ONg4DXS9VulSlgF7SOzY7Hz1.jpg", runtime: 74, description: "Abandoned by her fiancé, an educated black woman with a traumatizing past dedicates herself to helping a near bankrupt school for impoverished black children.", tmdb_id: 77621, watch_provider_link: "https://www.themoviedb.org/movie/77621-within-our-gates/watch?locale=US" },
  { title: "The Phantom Carriage", director: "Victor Sjöström", year: 1921, list_number: 10, genre: "Drama", poster_url: "https://image.tmdb.org/t/p/w600_and_h900_bestv2/vmhMEj2d8JnKS5jzqJf4kYypKWN.jpg", runtime: 106, description: "An alcoholic, abusive ne'er-do-well is shown the error of his ways through a legend that dooms the last person to die on New Year's Eve before the clock strikes twelve to take the reins of Death's chariot and work tirelessly collecting fresh souls for the next year.", tmdb_id: 58129, watch_provider_link: "https://www.themoviedb.org/movie/58129-korkarlen/watch?locale=US" }
];
