/**
 * Script to convert movies from the GitHub JSON to our format
 * Usage: npx tsx scripts/convert-movies-data.ts <start> <end>
 * Example: npx tsx scripts/convert-movies-data.ts 0 10
 */

import fs from "fs/promises";

interface SourceMovie {
  title: string;
  director: string;
  year: string;
  tags: string;
  desc: string;
  img: string;
  length: string;
}

interface SourceData {
  movies: SourceMovie[];
}

interface MovieSeed {
  title: string;
  director: string;
  year: number;
  list_number: number;
  genre?: string;
  poster_url?: string;
  runtime?: number;
  description?: string;
}

function parseRuntime(length: string): number | undefined {
  // Parse "1h 15m" or "0h 15m" format to minutes
  const match = length.match(/(\d+)h\s*(\d+)m/);
  if (match) {
    const hours = parseInt(match[1]);
    const minutes = parseInt(match[2]);
    return hours * 60 + minutes;
  }
  return undefined;
}

async function convertMovies(startIndex: number, endIndex: number) {
  // Read source file
  const sourceData = JSON.parse(
    await fs.readFile("/tmp/movies-source.json", "utf-8")
  ) as SourceData;

  // Convert movies
  const convertedMovies: MovieSeed[] = sourceData.movies
    .slice(startIndex, endIndex)
    .map((movie, index) => ({
      title: movie.title,
      director: movie.director,
      year: parseInt(movie.year),
      list_number: startIndex + index + 1,
      genre: movie.tags || undefined,
      poster_url: movie.img || undefined,
      runtime: parseRuntime(movie.length),
      description: movie.desc || undefined,
    }));

  console.log(`Converted ${convertedMovies.length} movies (positions ${startIndex + 1} to ${endIndex})`);
  console.log("\nSample movie:");
  console.log(JSON.stringify(convertedMovies[0], null, 2));

  // Read current movies-list.ts
  const currentContent = await fs.readFile(
    "./scripts/seed-data/movies-list.ts",
    "utf-8"
  );

  // Extract existing array content
  const arrayMatch = currentContent.match(/export const moviesList: MovieSeed\[\] = \[([\s\S]*)\];/);

  let existingMovies: string[] = [];
  if (arrayMatch && arrayMatch[1].trim()) {
    // Parse existing entries
    const content = arrayMatch[1].trim();
    // Split by movie objects (this is a simple approach)
    const matches = content.match(/\{[^}]+\}/g);
    if (matches) {
      existingMovies = matches;
    }
  }

  // Add new movies
  const newMovieStrings = convertedMovies.map(
    (movie) =>
      `  { title: "${movie.title.replace(/"/g, '\\"')}", director: "${movie.director.replace(/"/g, '\\"')}", year: ${movie.year}, list_number: ${movie.list_number}, genre: ${movie.genre ? `"${movie.genre}"` : "undefined"}, poster_url: ${movie.poster_url ? `"${movie.poster_url}"` : "undefined"}, runtime: ${movie.runtime || "undefined"}, description: ${movie.description ? `"${movie.description.replace(/"/g, '\\"').replace(/\n/g, ' ')}"` : "undefined"} }`
  );

  const allMovies = [...existingMovies, ...newMovieStrings];

  // Generate new content
  const newContent = `/**
 * Source: "1001 Movies You Must See Before You Die" book
 * Data from: https://github.com/Rooyca/1001M/blob/master/builder/movies.json
 *
 * This file is auto-generated by scripts/convert-movies-data.ts
 */

export interface MovieSeed {
  title: string;
  director: string;
  year: number;
  list_number: number;
  genre?: string;
  poster_url?: string;
  runtime?: number;
}

export const moviesList: MovieSeed[] = [
${allMovies.join(",\n")}
];
`;

  // Write updated file
  await fs.writeFile("./scripts/seed-data/movies-list.ts", newContent);

  console.log(`\n✅ Updated movies-list.ts with ${convertedMovies.length} new movies`);
  console.log(`Total movies in list: ${allMovies.length}`);
}

// Get command line arguments
const args = process.argv.slice(2);
const startIndex = parseInt(args[0] || "0");
const endIndex = parseInt(args[1] || "10");

if (isNaN(startIndex) || isNaN(endIndex)) {
  console.error("Usage: npx tsx scripts/convert-movies-data.ts <start> <end>");
  console.error("Example: npx tsx scripts/convert-movies-data.ts 0 10");
  process.exit(1);
}

convertMovies(startIndex, endIndex).catch(console.error);
